apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kubectl
    image: marinyuk/kubectl:v-1.0.2
    command:
    - /bin/cat
    tty: true
    volumeMounts:
    - name: kube-config
      mountPath: /root/.kube/
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: kube-config
    secret:
      secretName: config-winmoney-stage-secret
      items:
      - key: config-winmoney-stage
        path: config